CREATE DATABASE smart_cart_proj;

DROP TABLE IF EXISTS smart_cart_transactions;

CREATE TABLE smart_cart_transactions (
    transaction_id SERIAL PRIMARY KEY,
    cart_id INT NOT NULL ,
    product_name VARCHAR(100),
    category VARCHAR(50),
    price NUMERIC(10,2),
    quantity INT NOT NULL,
	total_amount NUMERIC(10,2)
);
SELECT * FROM smart_cart_transactions;
---------------------------------------------------------------------------------------------
--Show all Dairy category products
SELECT * 
FROM smart_cart_transactions
WHERE category = 'Dairy';

--Get all products costing more than ₹100
SELECT product_name, price 
FROM smart_cart_transactions
WHERE price > 100;

--List all unique categories
SELECT DISTINCT category 
FROM smart_cart_transactions;

--List all items sorted by price (highest first)
SELECT product_name, price
FROM smart_cart_transactions
ORDER BY price DESC;

--------------------------------------------------------------------------------------------
--Find total revenue of the smart cart (sum of all carts)
SELECT SUM(total_amount) AS total_revenue
FROM smart_cart_transactions;

--Calculate total spend per cart
SELECT cart_id, SUM(total_amount) AS cart_total
FROM smart_cart_transactions
GROUP BY cart_id
ORDER BY cart_id;

--Count how many items each customer purchased
SELECT cart_id, COUNT(*) AS items_purchased
FROM smart_cart_transactions
GROUP BY cart_id
ORDER BY cart_id;

--Find the most purchased category (by number of items)
SELECT category, SUM(quantity) AS total_quantity
FROM smart_cart_transactions
GROUP BY category
ORDER BY total_quantity DESC;

--Find revenue generated by each category
SELECT category, SUM(total_amount) AS category_revenue
FROM smart_cart_transactions
GROUP BY category
ORDER BY category_revenue DESC;
-----------------------------------------------------------------------------------------------
--Top 5 most profitable products
SELECT category, SUM(total_amount) AS category_revenue
FROM smart_cart_transactions
GROUP BY category
ORDER BY category_revenue DESC;

--Find which cart bought the highest number of items
SELECT cart_id, SUM(quantity) AS total_items
FROM smart_cart_transactions
GROUP BY cart_id
ORDER BY total_items DESC
LIMIT 1;

--Find average spend per cart
SELECT AVG(cart_total) AS avg_cart_spend
FROM (
    SELECT cart_id, SUM(total_amount) AS cart_total
    FROM smart_cart_transactions
    GROUP BY cart_id
) AS subquery;

--Top category in terms of revenue
SELECT category, SUM(total_amount) AS revenue
FROM smart_cart_transactions
GROUP BY category
ORDER BY revenue DESC
LIMIT 1;

--Which items were purchased more than 2 times
SELECT product_name, COUNT(*) AS times_purchased
FROM smart_cart_transactions
GROUP BY product_name
HAVING COUNT(*) > 2;

--Find customers who bought more than ₹200 worth of products
SELECT cart_id, SUM(total_amount) AS total_spent
FROM smart_cart_transactions
GROUP BY cart_id
HAVING SUM(total_amount) > 200;

--Category-wise average price
SELECT category, AVG(price) AS avg_price
FROM smart_cart_transactions
GROUP BY category
ORDER BY avg_price DESC;

--Find duplicate products purchased across many carts
SELECT product_name, COUNT(DISTINCT cart_id) AS carts_purchased
FROM smart_cart_transactions
GROUP BY product_name
ORDER BY carts_purchased DESC;

--Products bought together in the same cart:
SELECT t1.cart_id, t1.product_name AS product_1, t2.product_name AS product_2
FROM smart_cart_transactions t1
JOIN smart_cart_transactions t2
ON t1.cart_id = t2.cart_id AND t1.product_name < t2.product_name
ORDER BY t1.cart_id;

